// flow-typed signature: 2be5c3d7336757697c60c1de7415ee26
// flow-typed version: <<STUB>>/server-static_v^2.0.5/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'server-static'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'server-static' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'server-static/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'server-static/lib/index.js' {
  declare module.exports: $Exports<'server-static/lib/index'>;
}
